### ISSUE TITLE
SIGBUS in bwrc on 32-bit ARM

### ISSUE THREAD

**Issue by OPNA2608** [open-watcom/open-watcom-v2#1017]
Actually on aarch64-linux hardware & OS, but using a 32-bit ARM compile environment:
```
[nix-shell:~/devel/source]$ gcc -dumpmachine
armv7l-unknown-linux-gnueabihf
```

This can properly compile 32-bit ARMv7 variants of other system packages, so I assume the environment & compiler are working properly.

---

I'm trying to bootstrap OW with the above environment, just to verify if 32-bit ARM support works. I'm currently on fe9dc2b029b90758486529f7c7fda80260839260, but the same error happens on 49ef695d81a4597376928c58fe7a9b409e0a7153. When it tries to use the newly built `bwrc` it raises a Bus error and aborts:
```
gcc -pipe -c -D_BLDVER=1300 -D_CYEAR=1980 -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses  -O -g  -o stidedrv.obj  -DNDEBUG -DBOOTSTRAP -D_M_ARM -D__LINUX_ARM__ -D__UNIX__ -D__FLAT__ -D__LINUX__ -DINSIDE_WLINK -DIDE_PGM     -DSTATIC_LINKAGE  -I. -I"../../../bld/wl/h" -I"../../../bld/dwarf/dw/h" -I"../../../bld/orl/h" -I"../../../bld/rc/rc/h" -I"../../../bld/wres/h" -I"../../../bld/lib_misc/h" -I"../../../bld/watcom/c"  -I"../../../bld/trmem" -I"../../../bld/watcom/h" ../../../bld/wl/c/stidedrv.c
gcc -pipe -c -D_BLDVER=1300 -D_CYEAR=1980 -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses  -O -g  -o idemsgfm.obj  -DNDEBUG -DBOOTSTRAP -D_M_ARM -D__LINUX_ARM__ -D__UNIX__ -D__FLAT__ -D__LINUX__ -DINSIDE_WLINK -DIDE_PGM       -I. -I"../../../bld/wl/h" -I"../../../bld/dwarf/dw/h" -I"../../../bld/orl/h" -I"../../../bld/rc/rc/h" -I"../../../bld/wres/h" -I"../../../bld/lib_misc/h" -I"../../../bld/watcom/c"  -I"../../../bld/trmem" -I"../../../bld/watcom/h" ../../../bld/watcom/c/idemsgfm.c
gcc -pipe -c -D_BLDVER=1300 -D_CYEAR=1980 -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses  -O -g  -o maindrv.obj  -DNDEBUG -DBOOTSTRAP -D_M_ARM -D__LINUX_ARM__ -D__UNIX__ -D__FLAT__ -D__LINUX__ -DINSIDE_WLINK -DIDE_PGM     -DDLL_NAME=bwlinkd  -I. -I"../../../bld/wl/h" -I"../../../bld/dwarf/dw/h" -I"../../../bld/orl/h" -I"../../../bld/rc/rc/h" -I"../../../bld/wres/h" -I"../../../bld/lib_misc/h" -I"../../../bld/watcom/c"  -I"../../../bld/trmem" -I"../../../bld/watcom/h" ../../../bld/wl/c/maindrv.c
bwrc -q -D_BLDVER=1300 -D_CYEAR=1980 -xb -r -bt=windows -zku0 -D__UNIX__ -D__LINUX__  ../../../bld/wl/h/wlink.rc -fo=wresui.res -I. -I"../../../bld/wl/h" -I"../../../bld/rc/rc/h"   -I"../../../bld/watcom/h"
Bus error
Error(E42): Last command making (wresui.res) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error
```

When I try to replicate the erroring `bwrc` invocation under `gdb`, this is what's being reported:
```
Program received signal SIGBUS, Bus error.
0x00011864 in doAction (state=<synthetic pointer>, yytoken=Y_RPAREN) at winytab.c:1522
1522	            *++(state->vsp) = yylval;
(gdb) bt
#0  0x00011864 in doAction (state=<synthetic pointer>, yytoken=Y_RPAREN) at winytab.c:1522
#1  doParse (resource_state=<optimized out>) at winytab.c:3320
#2  ParseWIN () at winytab.c:3344
#3  0x00020224 in Pass1 () at ../c/rc.c:125
#4  RCmain () at ../c/rc.c:186
#5  0x00030f90 in RCSpawn (fn=0x30f90 <RCSpawn+84>, fn@entry=0x5fe48) at ../c/rcspawn.c:52
#6  0x00030b14 in RCMainLine (opts=0x10 <error: Cannot access memory at address 0x10>, opts@entry=0x0, argc=199444, argc@entry=16, argv=0x0, argv@entry=0xfffec584) at ../c/ideentry.c:284
#7  0x00030de4 in IDERunYourSelfArgv (hdl=<optimized out>, argc=argc@entry=16, argv=argv@entry=0xfffec584, fatalerr=0xfffec3ee, fatalerr@entry=0xfffec3e6) at ../c/ideentry.c:383
#8  0x0003748c in IdeDrvExecDLLArgv (inf=0x6004c <info>, argc=16, argv=0xfffec584) at ../../../../bld/watcom/c/idedrv.c:644
#9  0x00036fe4 in main (argc=<optimized out>, argv=<optimized out>) at ../c/maindrv.c:77
```

It looks to me like `*++(state->vsp)` leads to an unaligned memory access, which triggers a [SIGBUS (Bus error) because it's not supported on (32-bit?) ARM](https://en.wikipedia.org/wiki/Bus_error#Unaligned_access). Though I'm just speculating.

**Comment by jmalak** [comment]
I am sorry, I have no access to ARM architecture system that I can not identify source of problem.
I don't see unaligned pointer problem on this variable. I expect that compiler should do appropriate alignment by default.
May be gcc compiler require some option for 32-bit ARM which is not defined in OW build system.
It is experimental build platform completely depending on contributors with ARM systems.
