### ISSUE TITLE
Some 64-bit Linux tools segfault

### ISSUE THREAD

**Issue by OPNA2608** [open-watcom/open-watcom-v2#693]
I'm trying to package OpenWatcom V2 for Nixpkgs (a cross-platform package manager, https://github.com/NixOS/nixpkgs/pull/124000) and I've run into some problems I'm hoping to resolve issue-by-issue.

First, some of the 64-bit Linux tools instantly crash with a segmentation fault when I try to run them:

- ms2wlink
- wfl
- wfl386

The 32-bit Linux versions of those tools (binl instead of binl64) work though.

**Comment by jmalak** [comment]
thanks for bug report.
I will check and fix it.
What Linux distribution you are using?

**Comment by OPNA2608** [comment]
It happens on both NixOS 20.09 and Ubuntu 18.04 with the package code I wrote.

GDB backtrace for `wfl` and `wfl386`:

```
Starting program: /nix/store/04y10qans07zwgcdbvnydp69av6jh31d-open-watcom-v2-unstable-2021-06-04/lib/openwatcom/binl64/wfl 

Program received signal SIGSEGV, Segmentation fault.
0x000000000040634e in _bgetcmd (buffer=buffer@entry=0x4e6970 "", len=2147483646, len@entry=2147483647) at ../c/clibext.c:1229
1229	   while( (word = *argv++) != NULL ) {
(gdb) bt
#0  0x000000000040634e in _bgetcmd (buffer=buffer@entry=0x4e6970 "", len=2147483646, len@entry=2147483647) at ../c/clibext.c:1229
#1  0x0000000000406486 in getcmd (buffer=buffer@entry=0x4e6970 "") at ../c/clibext.c:1270
#2  0x0000000000402e8a in main (argc=1, argv=0x7fffffffac48) at ../../c/wfl.c:356
```

And for `ms2wlink`:
```
Starting program: /nix/store/04y10qans07zwgcdbvnydp69av6jh31d-open-watcom-v2-unstable-2021-06-04/lib/openwatcom/binl64/ms2wlink 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000406306 in _bgetcmd (buffer=buffer@entry=0x4ce6d0 "", len=2147483646, len@entry=2147483647) at ../c/clibext.c:1229
1229	   while( (word = *argv++) != NULL ) {
(gdb) bt
#0  0x0000000000406306 in _bgetcmd (buffer=buffer@entry=0x4ce6d0 "", len=2147483646, len@entry=2147483647) at ../c/clibext.c:1229
#1  0x000000000040643e in getcmd (buffer=0x4ce6d0 "") at ../c/clibext.c:1270
#2  0x000000000040492b in InitParsing () at ../c/parsems.c:71
#3  0x000000000040410c in DoConvert () at ../c/ms2wlink.c:188
#4  0x0000000000405a4d in Spawn (fn=fn@entry=0x404106 <DoConvert>) at ../c/utils.c:346
#5  0x00000000004042f0 in main () at ../c/ms2wlink.c:201
```

**Comment by jmalak** [comment]
it is fixed by commits 
ddee0b16f8e296dd69cdf0541b711362fbc6e850 
and 
965bea2f42aff71f4ef6a11c7207e855aa2e4633

**Comment by OPNA2608** [comment]
Works now, thanks!
